### ISSUE TITLE
Fetching characters can result in KeyError exception

### ISSUE THREAD

**Issue by spacez320** [nxtlo/aiobungie#302]
### Long story short.

When attempting to call `client.fetch_profile`, I'd receive a `KeyError: 'emblemBackgroundPath'` exception.

### Expected Result

`client.fetch_profile` to succeed.

### Actual Result

```
Traceback (most recent call last):
  File "/home/matthew/workspace/personal/chronicle/main.py", line 37, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/matthew/workspace/personal/chronicle/main.py", line 19, in main
    player_profile = await client.fetch_profile(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/.cache/pypoetry/virtualenvs/chronicle-FvDPkhce-py3.11/lib/python3.11/site-packages/aiobungie/client.py", line 370, in fetch_profile
    return self.factory.deserialize_components(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/.cache/pypoetry/virtualenvs/chronicle-FvDPkhce-py3.11/lib/python3.11/site-packages/aiobungie/internal/factory.py", line 1052, in deserialize_components
    characters = self.deserialize_characters(raw_characters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/.cache/pypoetry/virtualenvs/chronicle-FvDPkhce-py3.11/lib/python3.11/site-packages/aiobungie/internal/factory.py", line 844, in deserialize_characters
    return {
           ^
  File "/home/matthew/.cache/pypoetry/virtualenvs/chronicle-FvDPkhce-py3.11/lib/python3.11/site-packages/aiobungie/internal/factory.py", line 845, in <dictcomp>
    int(char_id): self._set_character_attrs(char)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matthew/.cache/pypoetry/virtualenvs/chronicle-FvDPkhce-py3.11/lib/python3.11/site-packages/aiobungie/internal/factory.py", line 392, in _set_character_attrs
    emblem=assets.Image(str(payload["emblemBackgroundPath"])),
                            ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'emblemBackgroundPath'
```

### System info

```
 chronicle $ uname -a
Linux icarus.eudaimonia.io 6.5.9-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 25 20:40:49 UTC 2023 x86_64 GNU/Linux
matthew@icarus // /home/matthew/workspace/personal/chronicle //  // lke57754-ctx // default
 chronicle $ cat /etc/fedora-release
Fedora release 38 (Thirty Eight)
matthew@icarus // /home/matthew/workspace/personal/chronicle //  // lke57754-ctx // default
 chronicle $ poetry run python --version
Python 3.11.6
```

### Further info

Seems simple to fix, currently opening a PR.

**Comment by spacez320** [comment]
Suggested a fix in https://github.com/nxtlo/aiobungie/pull/303
